{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language\/ErrorHandling"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Error handling"}],"type":"emphasis"},{"text":" is the process of responding to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and recovering from error conditions in your program."},{"type":"text","text":" "},{"type":"text","text":"Swift provides first-class support for"},{"text":" ","type":"text"},{"type":"text","text":"throwing, catching, propagating, and manipulating"},{"text":" ","type":"text"},{"text":"recoverable errors at runtime.","type":"text"}]},{"inlineContent":[{"type":"text","text":"Some operations"},{"text":" ","type":"text"},{"type":"text","text":"aren’t guaranteed to always complete execution or produce a useful output."},{"type":"text","text":" "},{"type":"text","text":"Optionals are used to represent the absence of a value,"},{"text":" ","type":"text"},{"type":"text","text":"but when an operation fails,"},{"type":"text","text":" "},{"text":"it’s often useful to understand what caused the failure,","type":"text"},{"type":"text","text":" "},{"text":"so that your code can respond accordingly.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"As an example, consider the task of reading and processing data from a file on disk.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"There are a number of ways this task can fail, including"},{"text":" ","type":"text"},{"type":"text","text":"the file not existing at the specified path,"},{"type":"text","text":" "},{"type":"text","text":"the file not having read permissions, or"},{"type":"text","text":" "},{"type":"text","text":"the file not being encoded in a compatible format."},{"text":" ","type":"text"},{"type":"text","text":"Distinguishing among these different situations"},{"text":" ","type":"text"},{"type":"text","text":"allows a program to resolve some errors"},{"type":"text","text":" "},{"type":"text","text":"and to communicate to the user any errors it can’t resolve."}],"type":"paragraph"},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error handling in Swift interoperates with error handling patterns"},{"text":" ","type":"text"},{"text":"that use the ","type":"text"},{"code":"NSError","type":"codeVoice"},{"text":" class in Cocoa and Objective-C.","type":"text"},{"type":"text","text":" "},{"text":"For more information about this class,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"see "},{"identifier":"https:\/\/developer.apple.com\/documentation\/swift\/cocoa_design_patterns\/handling_cocoa_errors_in_swift","isActive":true,"type":"reference"},{"type":"text","text":"."}]}],"name":"Note"},{"text":"Representar y arrojar errores","type":"heading","anchor":"Representar-y-arrojar-errores","level":2},{"type":"paragraph","inlineContent":[{"text":"In Swift, errors are represented by","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"values of types that conform to the "},{"type":"codeVoice","code":"Error"},{"text":" protocol.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This empty protocol indicates that a type"},{"text":" ","type":"text"},{"type":"text","text":"can be used for error handling."}]},{"inlineContent":[{"type":"text","text":"Swift enumerations are particularly well suited to modeling"},{"type":"text","text":" "},{"type":"text","text":"a group of related error conditions,"},{"type":"text","text":" "},{"type":"text","text":"with associated values allowing for additional information"},{"type":"text","text":" "},{"type":"text","text":"about the nature of an error to be communicated."},{"type":"text","text":" "},{"type":"text","text":"For example, here’s how you might represent the error conditions"},{"text":" ","type":"text"},{"type":"text","text":"of operating a vending machine inside a game:"}],"type":"paragraph"},{"syntax":"swift","code":["enum VendingMachineError: Error {","    case invalidSelection","    case insufficientFunds(coinsNeeded: Int)","    case outOfStock","}"],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"Throwing an error lets you indicate that something unexpected happened","type":"text"},{"type":"text","text":" "},{"text":"and the normal flow of execution can’t continue.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You use a "},{"type":"codeVoice","code":"throw"},{"text":" statement to throw an error.","type":"text"},{"type":"text","text":" "},{"text":"For example,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the following code throws an error to indicate"},{"type":"text","text":" "},{"text":"that five additional coins are needed by the vending machine:","type":"text"}]},{"syntax":"swift","type":"codeListing","code":["throw VendingMachineError.insufficientFunds(coinsNeeded: 5)"]},{"type":"heading","level":2,"text":"Manejo de errores","anchor":"Manejo-de-errores"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When an error is thrown,"},{"text":" ","type":"text"},{"type":"text","text":"some surrounding piece of code must be responsible"},{"type":"text","text":" "},{"text":"for handling the error —","type":"text"},{"type":"text","text":" "},{"type":"text","text":"for example, by correcting the problem,"},{"text":" ","type":"text"},{"text":"trying an alternative approach,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"or informing the user of the failure."}]},{"inlineContent":[{"text":"There are four ways to handle errors in Swift.","type":"text"},{"type":"text","text":" "},{"text":"You can propagate the error from a function to the code that calls that function,","type":"text"},{"type":"text","text":" "},{"text":"handle the error using a ","type":"text"},{"type":"codeVoice","code":"do"},{"text":"-","type":"text"},{"type":"codeVoice","code":"catch"},{"text":" statement,","type":"text"},{"text":" ","type":"text"},{"text":"handle the error as an optional value,","type":"text"},{"type":"text","text":" "},{"text":"or assert that the error will not occur.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Each approach is described in a section below."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"When a function throws an error,"},{"type":"text","text":" "},{"type":"text","text":"it changes the flow of your program,"},{"type":"text","text":" "},{"type":"text","text":"so it’s important that you can quickly identify places in your code that can throw errors."},{"type":"text","text":" "},{"type":"text","text":"To identify these places in your code, write the "},{"type":"codeVoice","code":"try"},{"text":" keyword —","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"or the "},{"type":"codeVoice","code":"try?"},{"type":"text","text":" or "},{"code":"try!","type":"codeVoice"},{"text":" variation —","type":"text"},{"text":" ","type":"text"},{"text":"before a piece of code that calls a function, method, or initializer that can throw an error.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"These keywords are described in the sections below."}],"type":"paragraph"},{"style":"note","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error handling in Swift resembles exception handling in other languages,"},{"type":"text","text":" "},{"text":"with the use of the ","type":"text"},{"type":"codeVoice","code":"try"},{"text":", ","type":"text"},{"type":"codeVoice","code":"catch"},{"type":"text","text":" and "},{"type":"codeVoice","code":"throw"},{"text":" keywords.","type":"text"},{"text":" ","type":"text"},{"text":"Unlike exception handling in many languages —","type":"text"},{"type":"text","text":" "},{"type":"text","text":"including Objective-C —"},{"type":"text","text":" "},{"type":"text","text":"error handling in Swift doesn’t involve unwinding the call stack,"},{"type":"text","text":" "},{"type":"text","text":"a process that can be computationally expensive."},{"text":" ","type":"text"},{"type":"text","text":"As such, the performance characteristics"},{"type":"text","text":" "},{"text":"of a ","type":"text"},{"type":"codeVoice","code":"throw"},{"type":"text","text":" statement"},{"type":"text","text":" "},{"text":"are comparable to those of a ","type":"text"},{"type":"codeVoice","code":"return"},{"type":"text","text":" statement."}]}],"type":"aside"},{"level":3,"anchor":"Propagaci%C3%B3n-de-errores-mediante-funciones-que-arrojan-errores","type":"heading","text":"Propagación de errores mediante funciones que arrojan errores"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To indicate that a function, method, or initializer can throw an error,"},{"type":"text","text":" "},{"type":"text","text":"you write the "},{"code":"throws","type":"codeVoice"},{"type":"text","text":" keyword in the function’s declaration"},{"text":" ","type":"text"},{"text":"after its parameters.","type":"text"},{"type":"text","text":" "},{"text":"A function marked with ","type":"text"},{"code":"throws","type":"codeVoice"},{"text":" is called a ","type":"text"},{"inlineContent":[{"text":"throwing function","type":"text"}],"type":"emphasis"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"If the function specifies a return type,"},{"text":" ","type":"text"},{"type":"text","text":"you write the "},{"code":"throws","type":"codeVoice"},{"text":" keyword before the return arrow (","type":"text"},{"code":"->","type":"codeVoice"},{"text":").","type":"text"}]},{"code":["func canThrowErrors() throws -> String","","func cannotThrowErrors() -> String"],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"A throwing function propagates errors that are thrown inside of it","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to the scope from which it’s called."}]},{"style":"note","name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Only throwing functions can propagate errors."},{"text":" ","type":"text"},{"type":"text","text":"Any errors thrown inside a nonthrowing function"},{"text":" ","type":"text"},{"type":"text","text":"must be handled inside the function."}]}]},{"inlineContent":[{"text":"In the example below,","type":"text"},{"type":"text","text":" "},{"text":"the ","type":"text"},{"type":"codeVoice","code":"VendingMachine"},{"type":"text","text":" class has a "},{"type":"codeVoice","code":"vend(itemNamed:)"},{"type":"text","text":" method"},{"text":" ","type":"text"},{"type":"text","text":"that throws an appropriate "},{"code":"VendingMachineError","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"if the requested item isn’t available,"},{"text":" ","type":"text"},{"text":"is out of stock,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"or has a cost that exceeds the current deposited amount:"}],"type":"paragraph"},{"code":["struct Item {","    var price: Int","    var count: Int","}","","class VendingMachine {","    var inventory = [","        \"Candy Bar\": Item(price: 12, count: 7),","        \"Chips\": Item(price: 10, count: 4),","        \"Pretzels\": Item(price: 7, count: 11)","    ]","    var coinsDeposited = 0","","    func vend(itemNamed name: String) throws {","        guard let item = inventory[name] else {","            throw VendingMachineError.invalidSelection","        }","","        guard item.count > 0 else {","            throw VendingMachineError.outOfStock","        }","","        guard item.price <= coinsDeposited else {","            throw VendingMachineError.insufficientFunds(coinsNeeded: item.price - coinsDeposited)","        }","","        coinsDeposited -= item.price","","        var newItem = item","        newItem.count -= 1","        inventory[name] = newItem","","        print(\"Dispensing \\(name)\")","    }","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"The implementation of the ","type":"text"},{"type":"codeVoice","code":"vend(itemNamed:)"},{"type":"text","text":" method"},{"type":"text","text":" "},{"type":"text","text":"uses "},{"type":"codeVoice","code":"guard"},{"type":"text","text":" statements to exit the method early and throw appropriate errors"},{"text":" ","type":"text"},{"text":"if any of the requirements for purchasing a snack aren’t met.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Because a "},{"code":"throw","type":"codeVoice"},{"type":"text","text":" statement immediately transfers program control,"},{"type":"text","text":" "},{"text":"an item will be vended only if all of these requirements are met.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Because the ","type":"text"},{"type":"codeVoice","code":"vend(itemNamed:)"},{"text":" method propagates any errors it throws,","type":"text"},{"text":" ","type":"text"},{"text":"any code that calls this method must either handle the errors —","type":"text"},{"type":"text","text":" "},{"text":"using a ","type":"text"},{"type":"codeVoice","code":"do"},{"text":"-","type":"text"},{"code":"catch","type":"codeVoice"},{"text":" statement, ","type":"text"},{"type":"codeVoice","code":"try?"},{"text":", or ","type":"text"},{"code":"try!","type":"codeVoice"},{"text":"—","type":"text"},{"text":" ","type":"text"},{"text":"or continue to propagate them.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"For example,"},{"text":" ","type":"text"},{"type":"text","text":"the "},{"type":"codeVoice","code":"buyFavoriteSnack(person:vendingMachine:)"},{"type":"text","text":" in the example below"},{"text":" ","type":"text"},{"text":"is also a throwing function,","type":"text"},{"type":"text","text":" "},{"text":"and any errors that the ","type":"text"},{"code":"vend(itemNamed:)","type":"codeVoice"},{"type":"text","text":" method throws will"},{"type":"text","text":" "},{"type":"text","text":"propagate up to the point where the "},{"type":"codeVoice","code":"buyFavoriteSnack(person:vendingMachine:)"},{"text":" function is called.","type":"text"}]},{"type":"codeListing","code":["let favoriteSnacks = [","    \"Alice\": \"Chips\",","    \"Bob\": \"Licorice\",","    \"Eve\": \"Pretzels\",","]","func buyFavoriteSnack(person: String, vendingMachine: VendingMachine) throws {","    let snackName = favoriteSnacks[person] ?? \"Candy Bar\"","    try vendingMachine.vend(itemNamed: snackName)","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In this example,"},{"type":"text","text":" "},{"text":"the ","type":"text"},{"code":"buyFavoriteSnack(person: vendingMachine:)","type":"codeVoice"},{"text":" function looks up a given person’s favorite snack","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and tries to buy it for them by calling the "},{"type":"codeVoice","code":"vend(itemNamed:)"},{"type":"text","text":" method."},{"type":"text","text":" "},{"text":"Because the ","type":"text"},{"type":"codeVoice","code":"vend(itemNamed:)"},{"type":"text","text":" method can throw an error,"},{"text":" ","type":"text"},{"type":"text","text":"it’s called with the "},{"type":"codeVoice","code":"try"},{"type":"text","text":" keyword in front of it."}]},{"type":"paragraph","inlineContent":[{"text":"Throwing initializers can propagate errors in the same way as throwing functions.","type":"text"},{"type":"text","text":" "},{"text":"For example,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the initializer for the "},{"type":"codeVoice","code":"PurchasedSnack"},{"type":"text","text":" structure in the listing below"},{"text":" ","type":"text"},{"text":"calls a throwing function as part of the initialization process,","type":"text"},{"type":"text","text":" "},{"text":"and it handles any errors that it encounters by propagating them to its caller.","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["struct PurchasedSnack {","    let name: String","    init(name: String, vendingMachine: VendingMachine) throws {","        try vendingMachine.vend(itemNamed: name)","        self.name = name","    }","}"]},{"type":"heading","text":"Manejo de errores mediante do-catch","anchor":"Manejo-de-errores-mediante-do-catch","level":3},{"inlineContent":[{"text":"You use a ","type":"text"},{"type":"codeVoice","code":"do"},{"text":"-","type":"text"},{"code":"catch","type":"codeVoice"},{"type":"text","text":" statement to handle errors"},{"text":" ","type":"text"},{"text":"by running a block of code.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If an error is thrown by the code in the "},{"type":"codeVoice","code":"do"},{"text":" clause,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"it’s matched against the "},{"type":"codeVoice","code":"catch"},{"text":" clauses","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to determine which one of them can handle the error."}],"type":"paragraph"},{"inlineContent":[{"text":"Here is the general form of a ","type":"text"},{"code":"do","type":"codeVoice"},{"type":"text","text":"-"},{"type":"codeVoice","code":"catch"},{"type":"text","text":" statement:"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["do {","    try <#expression#>","    <#statements#>","} catch <#pattern 1#> {","    <#statements#>","} catch <#pattern 2#> where <#condition#> {","    <#statements#>","} catch <#pattern 3#>, <#pattern 4#> where <#condition#> {","    <#statements#>","} catch {","    <#statements#>","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You write a pattern after "},{"code":"catch","type":"codeVoice"},{"text":" to indicate what errors","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"that clause can handle."},{"text":" ","type":"text"},{"type":"text","text":"If a "},{"code":"catch","type":"codeVoice"},{"type":"text","text":" clause doesn’t have a pattern,"},{"text":" ","type":"text"},{"type":"text","text":"the clause matches any error"},{"text":" ","type":"text"},{"type":"text","text":"and binds the error to a local constant named "},{"code":"error","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For more information about pattern matching,"},{"type":"text","text":" "},{"type":"text","text":"see "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language\/Patterns"},{"type":"text","text":"."}]},{"inlineContent":[{"type":"text","text":"For example, the following code matches against all three cases"},{"text":" ","type":"text"},{"text":"of the ","type":"text"},{"type":"codeVoice","code":"VendingMachineError"},{"text":" enumeration.","type":"text"}],"type":"paragraph"},{"syntax":"swift","type":"codeListing","code":["var vendingMachine = VendingMachine()","vendingMachine.coinsDeposited = 8","do {","    try buyFavoriteSnack(person: \"Alice\", vendingMachine: vendingMachine)","    print(\"Success! Yum.\")","} catch VendingMachineError.invalidSelection {","    print(\"Invalid Selection.\")","} catch VendingMachineError.outOfStock {","    print(\"Out of Stock.\")","} catch VendingMachineError.insufficientFunds(let coinsNeeded) {","    print(\"Insufficient funds. Please insert an additional \\(coinsNeeded) coins.\")","} catch {","    print(\"Unexpected error: \\(error).\")","}","\/\/ Prints \"Insufficient funds. Please insert an additional 2 coins.\""]},{"inlineContent":[{"type":"text","text":"In the above example,"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"codeVoice","code":"buyFavoriteSnack(person:vendingMachine:)"},{"type":"text","text":" function is called in a "},{"type":"codeVoice","code":"try"},{"type":"text","text":" expression,"},{"text":" ","type":"text"},{"type":"text","text":"because it can throw an error."},{"type":"text","text":" "},{"text":"If an error is thrown,","type":"text"},{"type":"text","text":" "},{"text":"execution immediately transfers to the ","type":"text"},{"type":"codeVoice","code":"catch"},{"type":"text","text":" clauses,"},{"type":"text","text":" "},{"type":"text","text":"which decide whether to allow propagation to continue."},{"type":"text","text":" "},{"type":"text","text":"If no pattern is matched, the error gets caught by the final "},{"code":"catch","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"clause and is bound to a local "},{"code":"error","type":"codeVoice"},{"text":" constant.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If no error is thrown,"},{"type":"text","text":" "},{"text":"the remaining statements in the ","type":"text"},{"code":"do","type":"codeVoice"},{"type":"text","text":" statement are executed."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"catch"},{"text":" clauses don’t have to handle every possible error","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"that the code in the "},{"code":"do","type":"codeVoice"},{"text":" clause can throw.","type":"text"},{"text":" ","type":"text"},{"text":"If none of the ","type":"text"},{"type":"codeVoice","code":"catch"},{"type":"text","text":" clauses handle the error,"},{"type":"text","text":" "},{"type":"text","text":"the error propagates to the surrounding scope."},{"type":"text","text":" "},{"text":"However, the propagated error","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"must be handled by "},{"type":"emphasis","inlineContent":[{"text":"some","type":"text"}]},{"text":" surrounding scope.","type":"text"},{"type":"text","text":" "},{"text":"In a nonthrowing function,","type":"text"},{"type":"text","text":" "},{"text":"an enclosing ","type":"text"},{"type":"codeVoice","code":"do"},{"type":"text","text":"-"},{"code":"catch","type":"codeVoice"},{"type":"text","text":" statement"},{"text":" ","type":"text"},{"text":"must handle the error.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"In a throwing function,"},{"type":"text","text":" "},{"text":"either an enclosing ","type":"text"},{"type":"codeVoice","code":"do"},{"type":"text","text":"-"},{"code":"catch","type":"codeVoice"},{"text":" statement","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"or the caller"},{"type":"text","text":" "},{"text":"must handle the error.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the error propagates to the top-level scope"},{"type":"text","text":" "},{"text":"without being handled,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"you’ll get a runtime error."}]},{"type":"paragraph","inlineContent":[{"text":"For example, the above example can be written so any","type":"text"},{"type":"text","text":" "},{"text":"error that isn’t a ","type":"text"},{"type":"codeVoice","code":"VendingMachineError"},{"type":"text","text":" is instead"},{"text":" ","type":"text"},{"text":"caught by the calling function:","type":"text"}]},{"syntax":"swift","code":["func nourish(with item: String) throws {","    do {","        try vendingMachine.vend(itemNamed: item)","    } catch is VendingMachineError {","        print(\"Couldn't buy that from the vending machine.\")","    }","}","","do {","    try nourish(with: \"Beet-Flavored Chips\")","} catch {","    print(\"Unexpected non-vending-machine-related error: \\(error)\")","}","\/\/ Prints \"Couldn't buy that from the vending machine.\""],"type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"In the ","type":"text"},{"code":"nourish(with:)","type":"codeVoice"},{"text":" function,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"if "},{"code":"vend(itemNamed:)","type":"codeVoice"},{"text":" throws an error that’s","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"one of the cases of the "},{"type":"codeVoice","code":"VendingMachineError"},{"type":"text","text":" enumeration,"},{"type":"text","text":" "},{"code":"nourish(with:)","type":"codeVoice"},{"text":" handles the error by printing a message.","type":"text"},{"text":" ","type":"text"},{"text":"Otherwise,","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"nourish(with:)"},{"type":"text","text":" propagates the error to its call site."},{"text":" ","type":"text"},{"text":"The error is then caught by the general ","type":"text"},{"type":"codeVoice","code":"catch"},{"type":"text","text":" clause."}]},{"inlineContent":[{"type":"text","text":"Another way to catch several related errors"},{"text":" ","type":"text"},{"type":"text","text":"is to list them after "},{"type":"codeVoice","code":"catch"},{"type":"text","text":", separated by commas."},{"type":"text","text":" "},{"type":"text","text":"For example:"}],"type":"paragraph"},{"code":["func eat(item: String) throws {","    do {","        try vendingMachine.vend(itemNamed: item)","    } catch VendingMachineError.invalidSelection, VendingMachineError.insufficientFunds, VendingMachineError.outOfStock {","        print(\"Invalid selection, out of stock, or not enough money.\")","    }","}"],"syntax":"swift","type":"codeListing"},{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"eat(item:)"},{"text":" function lists the vending machine errors to catch,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and its error text corresponds to the items in that list."},{"text":" ","type":"text"},{"text":"If any of the three listed errors are thrown,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"this "},{"code":"catch","type":"codeVoice"},{"type":"text","text":" clause handles them by printing a message."},{"type":"text","text":" "},{"text":"Any other errors are propagated to the surrounding scope,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"including any vending-machine errors that might be added later."}],"type":"paragraph"},{"text":"Conversión de errores en valores opcionales","level":3,"type":"heading","anchor":"Conversi%C3%B3n-de-errores-en-valores-opcionales"},{"type":"paragraph","inlineContent":[{"text":"You use ","type":"text"},{"code":"try?","type":"codeVoice"},{"text":" to handle an error by converting it to an optional value.","type":"text"},{"type":"text","text":" "},{"text":"If an error is thrown while evaluating the ","type":"text"},{"code":"try?","type":"codeVoice"},{"text":" expression,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the value of the expression is "},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"For example,"},{"type":"text","text":" "},{"text":"in the following code ","type":"text"},{"code":"x","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"y"},{"type":"text","text":" have the same value and behavior:"}]},{"syntax":"swift","type":"codeListing","code":["func someThrowingFunction() throws -> Int {","    \/\/ ...","}","","let x = try? someThrowingFunction()","","let y: Int?","do {","    y = try someThrowingFunction()","} catch {","    y = nil","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"code":"someThrowingFunction()","type":"codeVoice"},{"type":"text","text":" throws an error,"},{"type":"text","text":" "},{"type":"text","text":"the value of "},{"code":"x","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"y"},{"text":" is ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, the value of "},{"type":"codeVoice","code":"x"},{"type":"text","text":" and "},{"code":"y","type":"codeVoice"},{"type":"text","text":" is the value that the function returned."},{"text":" ","type":"text"},{"type":"text","text":"Note that "},{"type":"codeVoice","code":"x"},{"type":"text","text":" and "},{"code":"y","type":"codeVoice"},{"type":"text","text":" are an optional of whatever type "},{"code":"someThrowingFunction()","type":"codeVoice"},{"text":" returns.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Here the function returns an integer, so "},{"type":"codeVoice","code":"x"},{"text":" and ","type":"text"},{"code":"y","type":"codeVoice"},{"text":" are optional integers.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Using ","type":"text"},{"type":"codeVoice","code":"try?"},{"text":" lets you write concise error handling code","type":"text"},{"type":"text","text":" "},{"type":"text","text":"when you want to handle all errors in the same way."},{"text":" ","type":"text"},{"type":"text","text":"For example,"},{"text":" ","type":"text"},{"text":"the following code","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"uses several approaches to fetch data,"},{"text":" ","type":"text"},{"text":"or returns ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if all of the approaches fail."}]},{"code":["func fetchData() -> Data? {","    if let data = try? fetchDataFromDisk() { return data }","    if let data = try? fetchDataFromServer() { return data }","    return nil","}"],"type":"codeListing","syntax":"swift"},{"level":3,"anchor":"Inhabilitar-la-propagaci%C3%B3n-de-errores","type":"heading","text":"Inhabilitar la propagación de errores"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Sometimes you know a throwing function or method"},{"text":" ","type":"text"},{"type":"text","text":"won’t, in fact, throw an error at runtime."},{"text":" ","type":"text"},{"text":"On those occasions,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"you can write "},{"code":"try!","type":"codeVoice"},{"type":"text","text":" before the expression to disable error propagation"},{"text":" ","type":"text"},{"text":"and wrap the call in a runtime assertion that no error will be thrown.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If an error actually is thrown, you’ll get a runtime error."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For example, the following code uses a "},{"code":"loadImage(atPath:)","type":"codeVoice"},{"type":"text","text":" function,"},{"type":"text","text":" "},{"type":"text","text":"which loads the image resource at a given path"},{"text":" ","type":"text"},{"text":"or throws an error if the image can’t be loaded.","type":"text"},{"type":"text","text":" "},{"text":"In this case, because the image is shipped with the application,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"no error will be thrown at runtime,"},{"text":" ","type":"text"},{"text":"so it’s appropriate to disable error propagation.","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["let photo = try! loadImage(atPath: \".\/Resources\/John Appleseed.jpg\")"]},{"type":"heading","text":"Especificando acciones de limpieza","level":2,"anchor":"Especificando-acciones-de-limpieza"},{"inlineContent":[{"type":"text","text":"You use a "},{"code":"defer","type":"codeVoice"},{"type":"text","text":" statement to execute a set of statements"},{"type":"text","text":" "},{"text":"just before code execution leaves the current block of code.","type":"text"},{"text":" ","type":"text"},{"text":"This statement lets you do any necessary cleanup","type":"text"},{"type":"text","text":" "},{"text":"that should be performed regardless","type":"text"},{"type":"text","text":" "},{"type":"text","text":"of "},{"inlineContent":[{"type":"text","text":"how"}],"type":"emphasis"},{"text":" execution leaves the current block of code —","type":"text"},{"type":"text","text":" "},{"type":"text","text":"whether it leaves because an error was thrown"},{"type":"text","text":" "},{"type":"text","text":"or because of a statement such as "},{"code":"return","type":"codeVoice"},{"type":"text","text":" or "},{"code":"break","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For example, you can use a "},{"code":"defer","type":"codeVoice"},{"type":"text","text":" statement"},{"type":"text","text":" "},{"text":"to ensure that file descriptors are closed","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and manually allocated memory is freed."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"defer"},{"type":"text","text":" statement defers execution until the current scope is exited."},{"type":"text","text":" "},{"text":"This statement consists of the ","type":"text"},{"type":"codeVoice","code":"defer"},{"text":" keyword and the statements to be executed later.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The deferred statements may not contain any code"},{"text":" ","type":"text"},{"text":"that would transfer control out of the statements,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"such as a "},{"code":"break","type":"codeVoice"},{"type":"text","text":" or a "},{"type":"codeVoice","code":"return"},{"text":" statement,","type":"text"},{"text":" ","type":"text"},{"text":"or by throwing an error.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Deferred actions are executed in the reverse of"},{"text":" ","type":"text"},{"text":"the order that they’re written in your source code.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"That is, the code in the first "},{"code":"defer","type":"codeVoice"},{"type":"text","text":" statement executes last,"},{"text":" ","type":"text"},{"text":"the code in the second ","type":"text"},{"type":"codeVoice","code":"defer"},{"type":"text","text":" statement executes second to last,"},{"type":"text","text":" "},{"type":"text","text":"and so on."},{"type":"text","text":" "},{"type":"text","text":"The last "},{"code":"defer","type":"codeVoice"},{"type":"text","text":" statement in source code order executes first."}]},{"code":["func processFile(filename: String) throws {","    if exists(filename) {","        let file = open(filename)","        defer {","            close(file)","        }","        while let line = try file.readline() {","            \/\/ Work with the file.","        }","        \/\/ close(file) is called here, at the end of the scope.","    }","}"],"syntax":"swift","type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"The above example uses a ","type":"text"},{"type":"codeVoice","code":"defer"},{"type":"text","text":" statement"},{"type":"text","text":" "},{"type":"text","text":"to ensure that the "},{"type":"codeVoice","code":"open(_:)"},{"text":" function","type":"text"},{"text":" ","type":"text"},{"text":"has a corresponding call to ","type":"text"},{"type":"codeVoice","code":"close(_:)"},{"text":".","type":"text"}]},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You can use a "},{"type":"codeVoice","code":"defer"},{"type":"text","text":" statement"},{"type":"text","text":" "},{"text":"even when no error handling code is involved.","type":"text"}]}],"name":"Note","style":"note"},{"name":"Software Beta","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"}]},{"inlineContent":[{"type":"text","text":"Esta documentación contiene información preliminar sobre una API o tecnología en desarrollo. Esta información está sujeta a cambios, y todo software implementado en conformidad con esta documentación debe ser testeado con el software final del sistema operativo."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Conoce más acerca del uso del "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/es\/support\/beta-software\/"},{"type":"text","text":"."}],"type":"paragraph"}],"type":"aside","style":"note"}],"kind":"content"}],"sections":[],"abstract":[{"type":"text","text":"Respond to and recover from errors."}],"hierarchy":{"paths":[["doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language"]]},"kind":"article","metadata":{"title":"Manejo de errores"},"references":{"https://developer.apple.com/documentation/swift/cocoa_design_patterns/handling_cocoa_errors_in_swift":{"titleInlineContent":[{"text":"Handling Cocoa Errors in Swift","type":"text"}],"title":"Handling Cocoa Errors in Swift","type":"link","url":"https:\/\/developer.apple.com\/documentation\/swift\/cocoa_design_patterns\/handling_cocoa_errors_in_swift","identifier":"https:\/\/developer.apple.com\/documentation\/swift\/cocoa_design_patterns\/handling_cocoa_errors_in_swift"},"doc://org.swift.tspl/documentation/The-Swift-Programming-Language/Patterns":{"identifier":"doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language\/Patterns","url":"\/documentation\/the-swift-programming-language\/patterns","type":"topic","role":"article","abstract":[{"text":"Match and destructure values.","type":"text"}],"title":"Patrones","kind":"article"},"doc://org.swift.tspl/documentation/The-Swift-Programming-Language":{"kind":"article","role":"collection","url":"\/documentation\/the-swift-programming-language","abstract":[],"title":"The Swift Programming Language (6)","type":"topic","identifier":"doc:\/\/org.swift.tspl\/documentation\/The-Swift-Programming-Language"},"https://developer.apple.com/es/support/beta-software/":{"titleInlineContent":[{"type":"text","text":"software beta de Apple"}],"title":"software beta de Apple","type":"link","url":"https:\/\/developer.apple.com\/es\/support\/beta-software\/","identifier":"https:\/\/developer.apple.com\/es\/support\/beta-software\/"}}}